export const SET_APP_LIST = 'SET_APP_LIST';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
export const UPDATE_STATUS_LOAD = 'UPDATE_STATUS_LOAD';
export const UPDATE_TITLE_PAGE = 'UPDATE_TITLE_PAGE';