export const SET_APP_LIST = 'SET_APP_LIST';
export const REMOVE_APPLICATION = 'REMOVE_APPLICATION';
export const UPDATE_TITLE_PAGE = 'UPDATE_TITLE_PAGE';
export const UPDATE_PRIORITY = 'UPDATE_PRIORITY';
export const SET_EXIST_EXECUTERS = 'SET_EXIST_EXECUTERS';


export const UPDATE_STATUS_LOAD = 'UPDATE_STATUS_LOAD';

export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_STATUS_LOGIN = 'UPDATE_STATUS_LOGIN';